version: '2'
services:

  zookeeper:
    image: mesoscloud/zookeeper:3.4.8-ubuntu-14.04
    container_name: zookeeper_1
    hostname: zookeeper${MYID}
    network_mode: host
    restart: always
    environment:
      - MYID=${MYID}
      - SERVERS=${SERVER1},${SERVER2},${SERVER3}

  mesos-master:
    image: mesoscloud/mesos-master:0.28.1-ubuntu-14.04
    container_name: mesos-master_1
    hostname: mesos-master${MYID}
    network_mode: host
    restart: always
    environment:
      - MESOS_HOSTNAME=${HOSTIP}
      - MESOS_IP=${HOSTIP}
      - MESOS_QUORUM=2
      - MESOS_ZK=zk://${SERVER1}:2181,${SERVER2}:2181,${SERVER3}:2181/mesos
      - MESOS_LOG_DIR=/tmp/mesos
      - SECRET=123123
      - MESOS_AUTHENTICATE=true
      - MESOS_AUTHENTICATE_SLAVES=true
      - MESOS_CREDENTIALS=/tmp/credentials