version: '2'
services:
  cassandra:
    image: cassandra
    restart: always
    container_name: cassandra1
    hostname: cassandra
    network_mode: host
    privileged: true
    volumes:
      - /var/lib/cassandra:/var/lib/cassandra
    ports:
      - "9042:9042"
      - "7199:7199"


