version: '2'
services:
  mesos-slave:
    build: .
    image: mesos-slave:Spark1.6.0-Scala2.11
    restart: always
    container_name: mesos-slave_1
    network_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    environment:
      - MESOS_HOSTNAME=${HOSTIP}
      - MESOS_IP=${HOSTIP}
      - MESOS_MASTER=zk://${SERVER1}:2181,${SERVER2}:2181,${SERVER3}:2181/mesos
      - MESOS_LOG_DIR=/tmp/mesos
      - SECRET=123123
      - MESOS_CREDENTIAL=/tmp/credential



