- name: logstash server setup
  hosts: localhost
  gather_facts: no
  sudo: yes
  tasks:
    - git:
        repo: https://github.com/SandeepSarpe/mesos-zookeeper-cluster.git
        dest: /home/ubuntu/
    - docker_service:
        project_src: /home/ubuntu/ansible/logstash/logstash_server
  environment:
    LOGSTASH_SERVER_IP: 10.0.1.215
    LOGSTASH_SERVER_HOSTNAME: ec2-52-91-199-29.compute-1.amazonaws.com
    LOGSTASH_SERVER_NGINXPASS: loven
