- name: mesos-zookeeper cluster on Node1
  hosts: ec2-52-91-199-55.compute-1.amazonaws.com
  gather_facts: no
  sudo: yes
  tasks:
    - apt:
        name: python-yaml
    - apt:
        name: docker.io
        state: latest
        update_cache: yes
    - apt_key:
        keyserver: hkp://p80.pool.sks-keyservers.net:80
        id: 58118E89F3A912897C070ADBF76221572C52609D
    - shell: echo 'deb https://apt.dockerproject.org/repo ubuntu-trusty main' >> /etc/apt/sources.list.d/docker.list
    - apt:
        name: docker-engine
        update_cache: yes
        purge: yes
    - apt:
        name: python-pip
        force: yes
        update_cache: yes
    - pip:
        name: docker-compose
    - git:
        repo: https://github.com/SandeepSarpe/mesos-zookeeper-cluster.git
        dest: /home/ubuntu/diwo/
    - docker_service:
        project_src: /home/ubuntu/diwo/ansible/mesos_cluster/mesos_zookeeper_cluster
  environment:
    MYID: 1
    HOSTIP: 10.0.1.4
    SERVER1: 10.0.1.4
    SERVER2: 10.0.1.135
    SERVER3: 10.0.1.5

- name: mesos-zookeeper cluster on Node2
  hosts: ec2-54-173-215-166.compute-1.amazonaws.com
  gather_facts: no
  sudo: yes
  tasks:
    - apt:
        name: python-yaml
    - apt:
        name: docker.io
        state: latest
        update_cache: yes
    - apt_key:
        keyserver: hkp://p80.pool.sks-keyservers.net:80
        id: 58118E89F3A912897C070ADBF76221572C52609D
    - shell: echo 'deb https://apt.dockerproject.org/repo ubuntu-trusty main' >> /etc/apt/sources.list.d/docker.list
    - apt:
        name: docker-engine
        update_cache: yes
        purge: yes
    - apt:
        name: python-pip
        force: yes
        update_cache: yes
    - pip:
        name: docker-compose
    - git:
        repo: https://github.com/SandeepSarpe/mesos-zookeeper-cluster.git
        dest: /home/ubuntu/diwo/
    - docker_service:
        project_src: /home/ubuntu/diwo/ansible/mesos_cluster/mesos_zookeeper_cluster
  environment:
    MYID: 2
    HOSTIP: 10.0.1.135
    SERVER1: 10.0.1.4
    SERVER2: 10.0.1.135
    SERVER3: 10.0.1.5

- name: mesos-zookeeper cluster on Node2
  hosts: ec2-52-91-201-76.compute-1.amazonaws.com
  gather_facts: no
  sudo: yes
  tasks:
    - apt:
        name: python-yaml
    - apt:
        name: docker.io
        state: latest
        update_cache: yes
    - apt_key:
        keyserver: hkp://p80.pool.sks-keyservers.net:80
        id: 58118E89F3A912897C070ADBF76221572C52609D
    - shell: echo 'deb https://apt.dockerproject.org/repo ubuntu-trusty main' >> /etc/apt/sources.list.d/docker.list
    - apt:
        name: docker-engine
        update_cache: yes
        purge: yes
    - apt:
        name: python-pip
        force: yes
        update_cache: yes
    - pip:
        name: docker-compose
    - git:
        repo: https://github.com/SandeepSarpe/mesos-zookeeper-cluster.git
        dest: /home/ubuntu/diwo/
    - docker_service:
        project_src: /home/ubuntu/diwo/ansible/mesos_cluster/mesos_zookeeper_cluster
  environment:
    MYID: 3
    HOSTIP: 10.0.1.5
    SERVER1: 10.0.1.4
    SERVER2: 10.0.1.135
    SERVER3: 10.0.1.5
