- name: Create spark-job submitter on localhost
  hosts: localhost
  gather_facts: no
  sudo: yes
  tasks:
    - git:
        repo: https://github.com/SandeepSarpe/mesos-zookeeper-cluster.git
        dest: /home/ubuntu/diwo/
    - docker_service:
        project_src: /home/ubuntu/diwo/ansible/mesos_cluster/spark_job_submitter
