- name: Create spark-job submitter on Node4
  hosts: Node4
  gather_facts: no
  sudo: yes
  tasks:
    - apt:
        name: python-yaml
    - apt:
        name: docker.io
        state: latest
        update_cache: yes
    - apt_key:
        keyserver: hkp://p80.pool.sks-keyservers.net:80
        id: 58118E89F3A912897C070ADBF76221572C52609D
    - shell: echo 'deb https://apt.dockerproject.org/repo ubuntu-trusty main' >> /etc/apt/sources.list.d/docker.list
    - apt:
        name: docker-engine
        update_cache: yes
        purge: yes
    - apt:
        name: python-pip
        force: yes
        update_cache: yes
    - pip:
        name: docker-compose
    - shell: mkdir /home/diwo
    - git:
        repo: https://github.com/SandeepSarpe/mesos-zookeeper-cluster.git
        dest: /home/diwo/
    - docker_service:
        project_src: /home/diwo/ansible/mesos_cluster/spark_job_submitter